name: Technical Task
description: Template for technical implementation tasks
title: "[Technical]: "
labels: ["technical-task"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a technical task!

  - type: textarea
    id: technical-description
    attributes:
      label: Technical Description
      description: Provide a clear description of the technical task
      placeholder: Describe the technical task and its purpose...
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: List the technical requirements that must be met
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: Describe the technical approach and requirements
      placeholder: |
        - Technical approach
        - Required tools/libraries
        - Performance targets
        - Testing strategy

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any technical dependencies
      placeholder: |
        - Required libraries
        - Required configurations
        - Related issues

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: story-points
    attributes:
      label: Story Points
      options:
        - 1
        - 2
        - 3
        - 5
        - 8
        - 13
    validations:
      required: true
